
//INPUT PROPS
//webServerBase - Base URL of web server
var App = React.createClass({
  render: function() {
    var windowHeight  = $(window).innerHeight();
    var windowWidth   = $(window).innerWidth();
    var styles = {backgroundColor: "green",
                  width:            windowWidth,
                  height:           windowHeight};
    //return <div style={styles}>This was generated by React</div>;
    return <div style={styles}>
            <p>Window Height: {windowHeight}</p>
            <p>Window Width: {windowWidth}</p>
            <WelcomePage webServerBase={this.props.webServerBase}/>
           </div>;
  }
});
