
var Box = React.createClass({
  render: function() {
    var windowHeight  = $(window).outerHeight();
    var windowWidth   = $(window).outerWidth();
    var styles = {backgroundColor: "red",
                  width: "300px",
                  height: "200px"};
    return <div style={styles}>
              This was generated by React.
              <p>Window Height: {windowHeight}</p>
              <p>Window Width: {windowWidth}</p>
           </div>;
  }
});
//React.render(<Box />, document.getElementById("reacttesting"));
//console.log("========================================");
//console.log("BOX JSX ran");
//console.log("========================================");
