
var Box = React.createClass({
  render: function() {
    var styles = {backgroundColor: "red",
                  width: "50px",
                  height: "50px"};
    return <div style={styles}>This was generated by React</div>;
  }
});
React.render(<Box />, document.getElementById("reacttesting"));
console.log("========================================");
console.log("BOX JSX ran");
console.log("========================================");
